services:
  # Frontend Static Site
  - type: web
    name: mubarakway-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'self' https://*.telegram.org https://telegram.org"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: NODE_VERSION
        value: "20.17.0"

  # Backend API + Telegram Bot (Unified Service)
  - type: web
    name: mubarakway-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.17.0"
      - key: MONGODB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: WEB_APP_URL
        value: https://mubarakway-frontend.onrender.com
      - key: PORT
        value: "10000"
