services:
  # Frontend Static Site - Telegram Mini App
  - type: web
    name: mubarakway-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: ALLOWALL
      - path: /*
        name: Content-Security-Policy
        value: "frame-ancestors 'self' https://*.telegram.org https://telegram.org"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    envVars:
      - key: NODE_VERSION
        value: "20.17.0"
      - key: VITE_API_URL
        value: https://mubarakway-backend.onrender.com/api
      - key: VITE_QURAN_API_URL
        value: https://bot.e-replika.ru/api/v1
      - key: VITE_QURAN_API_TOKEN
        value: test_token_123
      - key: BACKEND_URL
        value: https://mubarakway-backend.onrender.com

  # Backend API + Telegram Bot (Unified Service)
  - type: web
    name: mubarakway-backend
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.17.0"
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WEB_APP_URL
        value: https://mubarakway-frontend.onrender.com
      - key: BACKEND_URL
        value: https://mubarakway-backend.onrender.com
      - key: VITE_API_URL
        value: https://mubarakway-backend.onrender.com
