# Frontend Static Site - Main Blueprint
type: web
env: static
name: mubarak-way-frontend
buildCommand: npm ci && npm run build
staticPublishPath: ./dist
pullRequestPreviewsEnabled: true
headers:
  - path: /*
    name: X-Frame-Options
    value: ALLOWALL
  - path: /*
    name: Content-Security-Policy
    value: "frame-ancestors 'self' https://*.telegram.org https://telegram.org"
  - path: /*
    name: X-Content-Type-Options
    value: nosniff
envVars:
  - key: NODE_VERSION
    value: "20.17.0"
  - key: VITE_APP_URL
    value: https://mubarak-way-frontend.onrender.com